/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapStaticDotxmlRouteImport } from './routes/sitemap-static[.]xml'
import { Route as SitemapDynamicDotxmlRouteImport } from './routes/sitemap-dynamic[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as KotowazaRouteImport } from './routes/kotowaza'
import { Route as KatakanaRouteImport } from './routes/katakana'
import { Route as KanjiRouteImport } from './routes/kanji'
import { Route as JoyoRouteImport } from './routes/joyo'
import { Route as JlptRouteImport } from './routes/jlpt'
import { Route as HiraganaRouteImport } from './routes/hiragana'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CharacterMasteryRouteImport } from './routes/character-mastery'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KatakanaLetterRouteImport } from './routes/katakana_.$letter'
import { Route as KanjiLetterRouteImport } from './routes/kanji_.$letter'
import { Route as JoyoGradeRouteImport } from './routes/joyo_.$grade'
import { Route as JlptNRouteImport } from './routes/jlpt_.$n'
import { Route as HiraganaLetterRouteImport } from './routes/hiragana_.$letter'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapStaticDotxmlRoute = SitemapStaticDotxmlRouteImport.update({
  id: '/sitemap-static.xml',
  path: '/sitemap-static.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDynamicDotxmlRoute = SitemapDynamicDotxmlRouteImport.update({
  id: '/sitemap-dynamic.xml',
  path: '/sitemap-dynamic.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const KotowazaRoute = KotowazaRouteImport.update({
  id: '/kotowaza',
  path: '/kotowaza',
  getParentRoute: () => rootRouteImport,
} as any)
const KatakanaRoute = KatakanaRouteImport.update({
  id: '/katakana',
  path: '/katakana',
  getParentRoute: () => rootRouteImport,
} as any)
const KanjiRoute = KanjiRouteImport.update({
  id: '/kanji',
  path: '/kanji',
  getParentRoute: () => rootRouteImport,
} as any)
const JoyoRoute = JoyoRouteImport.update({
  id: '/joyo',
  path: '/joyo',
  getParentRoute: () => rootRouteImport,
} as any)
const JlptRoute = JlptRouteImport.update({
  id: '/jlpt',
  path: '/jlpt',
  getParentRoute: () => rootRouteImport,
} as any)
const HiraganaRoute = HiraganaRouteImport.update({
  id: '/hiragana',
  path: '/hiragana',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterMasteryRoute = CharacterMasteryRouteImport.update({
  id: '/character-mastery',
  path: '/character-mastery',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KatakanaLetterRoute = KatakanaLetterRouteImport.update({
  id: '/katakana_/$letter',
  path: '/katakana/$letter',
  getParentRoute: () => rootRouteImport,
} as any)
const KanjiLetterRoute = KanjiLetterRouteImport.update({
  id: '/kanji_/$letter',
  path: '/kanji/$letter',
  getParentRoute: () => rootRouteImport,
} as any)
const JoyoGradeRoute = JoyoGradeRouteImport.update({
  id: '/joyo_/$grade',
  path: '/joyo/$grade',
  getParentRoute: () => rootRouteImport,
} as any)
const JlptNRoute = JlptNRouteImport.update({
  id: '/jlpt_/$n',
  path: '/jlpt/$n',
  getParentRoute: () => rootRouteImport,
} as any)
const HiraganaLetterRoute = HiraganaLetterRouteImport.update({
  id: '/hiragana_/$letter',
  path: '/hiragana/$letter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyze': typeof AnalyzeRoute
  '/character-mastery': typeof CharacterMasteryRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/hiragana': typeof HiraganaRoute
  '/jlpt': typeof JlptRoute
  '/joyo': typeof JoyoRoute
  '/kanji': typeof KanjiRoute
  '/katakana': typeof KatakanaRoute
  '/kotowaza': typeof KotowazaRoute
  '/quiz': typeof QuizRoute
  '/settings': typeof SettingsRoute
  '/sitemap-dynamic.xml': typeof SitemapDynamicDotxmlRoute
  '/sitemap-static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/$': typeof ApiSplatRoute
  '/hiragana/$letter': typeof HiraganaLetterRoute
  '/jlpt/$n': typeof JlptNRoute
  '/joyo/$grade': typeof JoyoGradeRoute
  '/kanji/$letter': typeof KanjiLetterRoute
  '/katakana/$letter': typeof KatakanaLetterRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyze': typeof AnalyzeRoute
  '/character-mastery': typeof CharacterMasteryRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/hiragana': typeof HiraganaRoute
  '/jlpt': typeof JlptRoute
  '/joyo': typeof JoyoRoute
  '/kanji': typeof KanjiRoute
  '/katakana': typeof KatakanaRoute
  '/kotowaza': typeof KotowazaRoute
  '/quiz': typeof QuizRoute
  '/settings': typeof SettingsRoute
  '/sitemap-dynamic.xml': typeof SitemapDynamicDotxmlRoute
  '/sitemap-static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/$': typeof ApiSplatRoute
  '/hiragana/$letter': typeof HiraganaLetterRoute
  '/jlpt/$n': typeof JlptNRoute
  '/joyo/$grade': typeof JoyoGradeRoute
  '/kanji/$letter': typeof KanjiLetterRoute
  '/katakana/$letter': typeof KatakanaLetterRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyze': typeof AnalyzeRoute
  '/character-mastery': typeof CharacterMasteryRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/hiragana': typeof HiraganaRoute
  '/jlpt': typeof JlptRoute
  '/joyo': typeof JoyoRoute
  '/kanji': typeof KanjiRoute
  '/katakana': typeof KatakanaRoute
  '/kotowaza': typeof KotowazaRoute
  '/quiz': typeof QuizRoute
  '/settings': typeof SettingsRoute
  '/sitemap-dynamic.xml': typeof SitemapDynamicDotxmlRoute
  '/sitemap-static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/$': typeof ApiSplatRoute
  '/hiragana_/$letter': typeof HiraganaLetterRoute
  '/jlpt_/$n': typeof JlptNRoute
  '/joyo_/$grade': typeof JoyoGradeRoute
  '/kanji_/$letter': typeof KanjiLetterRoute
  '/katakana_/$letter': typeof KatakanaLetterRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analyze'
    | '/character-mastery'
    | '/dashboard'
    | '/disclaimer'
    | '/hiragana'
    | '/jlpt'
    | '/joyo'
    | '/kanji'
    | '/katakana'
    | '/kotowaza'
    | '/quiz'
    | '/settings'
    | '/sitemap-dynamic.xml'
    | '/sitemap-static.xml'
    | '/sitemap.xml'
    | '/api/$'
    | '/hiragana/$letter'
    | '/jlpt/$n'
    | '/joyo/$grade'
    | '/kanji/$letter'
    | '/katakana/$letter'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analyze'
    | '/character-mastery'
    | '/dashboard'
    | '/disclaimer'
    | '/hiragana'
    | '/jlpt'
    | '/joyo'
    | '/kanji'
    | '/katakana'
    | '/kotowaza'
    | '/quiz'
    | '/settings'
    | '/sitemap-dynamic.xml'
    | '/sitemap-static.xml'
    | '/sitemap.xml'
    | '/api/$'
    | '/hiragana/$letter'
    | '/jlpt/$n'
    | '/joyo/$grade'
    | '/kanji/$letter'
    | '/katakana/$letter'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analyze'
    | '/character-mastery'
    | '/dashboard'
    | '/disclaimer'
    | '/hiragana'
    | '/jlpt'
    | '/joyo'
    | '/kanji'
    | '/katakana'
    | '/kotowaza'
    | '/quiz'
    | '/settings'
    | '/sitemap-dynamic.xml'
    | '/sitemap-static.xml'
    | '/sitemap.xml'
    | '/api/$'
    | '/hiragana_/$letter'
    | '/jlpt_/$n'
    | '/joyo_/$grade'
    | '/kanji_/$letter'
    | '/katakana_/$letter'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalyzeRoute: typeof AnalyzeRoute
  CharacterMasteryRoute: typeof CharacterMasteryRoute
  DashboardRoute: typeof DashboardRoute
  DisclaimerRoute: typeof DisclaimerRoute
  HiraganaRoute: typeof HiraganaRoute
  JlptRoute: typeof JlptRoute
  JoyoRoute: typeof JoyoRoute
  KanjiRoute: typeof KanjiRoute
  KatakanaRoute: typeof KatakanaRoute
  KotowazaRoute: typeof KotowazaRoute
  QuizRoute: typeof QuizRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDynamicDotxmlRoute: typeof SitemapDynamicDotxmlRoute
  SitemapStaticDotxmlRoute: typeof SitemapStaticDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiSplatRoute: typeof ApiSplatRoute
  HiraganaLetterRoute: typeof HiraganaLetterRoute
  JlptNRoute: typeof JlptNRoute
  JoyoGradeRoute: typeof JoyoGradeRoute
  KanjiLetterRoute: typeof KanjiLetterRoute
  KatakanaLetterRoute: typeof KatakanaLetterRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-static.xml': {
      id: '/sitemap-static.xml'
      path: '/sitemap-static.xml'
      fullPath: '/sitemap-static.xml'
      preLoaderRoute: typeof SitemapStaticDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-dynamic.xml': {
      id: '/sitemap-dynamic.xml'
      path: '/sitemap-dynamic.xml'
      fullPath: '/sitemap-dynamic.xml'
      preLoaderRoute: typeof SitemapDynamicDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kotowaza': {
      id: '/kotowaza'
      path: '/kotowaza'
      fullPath: '/kotowaza'
      preLoaderRoute: typeof KotowazaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katakana': {
      id: '/katakana'
      path: '/katakana'
      fullPath: '/katakana'
      preLoaderRoute: typeof KatakanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanji': {
      id: '/kanji'
      path: '/kanji'
      fullPath: '/kanji'
      preLoaderRoute: typeof KanjiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joyo': {
      id: '/joyo'
      path: '/joyo'
      fullPath: '/joyo'
      preLoaderRoute: typeof JoyoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jlpt': {
      id: '/jlpt'
      path: '/jlpt'
      fullPath: '/jlpt'
      preLoaderRoute: typeof JlptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiragana': {
      id: '/hiragana'
      path: '/hiragana'
      fullPath: '/hiragana'
      preLoaderRoute: typeof HiraganaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character-mastery': {
      id: '/character-mastery'
      path: '/character-mastery'
      fullPath: '/character-mastery'
      preLoaderRoute: typeof CharacterMasteryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katakana_/$letter': {
      id: '/katakana_/$letter'
      path: '/katakana/$letter'
      fullPath: '/katakana/$letter'
      preLoaderRoute: typeof KatakanaLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanji_/$letter': {
      id: '/kanji_/$letter'
      path: '/kanji/$letter'
      fullPath: '/kanji/$letter'
      preLoaderRoute: typeof KanjiLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joyo_/$grade': {
      id: '/joyo_/$grade'
      path: '/joyo/$grade'
      fullPath: '/joyo/$grade'
      preLoaderRoute: typeof JoyoGradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jlpt_/$n': {
      id: '/jlpt_/$n'
      path: '/jlpt/$n'
      fullPath: '/jlpt/$n'
      preLoaderRoute: typeof JlptNRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiragana_/$letter': {
      id: '/hiragana_/$letter'
      path: '/hiragana/$letter'
      fullPath: '/hiragana/$letter'
      preLoaderRoute: typeof HiraganaLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalyzeRoute: AnalyzeRoute,
  CharacterMasteryRoute: CharacterMasteryRoute,
  DashboardRoute: DashboardRoute,
  DisclaimerRoute: DisclaimerRoute,
  HiraganaRoute: HiraganaRoute,
  JlptRoute: JlptRoute,
  JoyoRoute: JoyoRoute,
  KanjiRoute: KanjiRoute,
  KatakanaRoute: KatakanaRoute,
  KotowazaRoute: KotowazaRoute,
  QuizRoute: QuizRoute,
  SettingsRoute: SettingsRoute,
  SitemapDynamicDotxmlRoute: SitemapDynamicDotxmlRoute,
  SitemapStaticDotxmlRoute: SitemapStaticDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiSplatRoute: ApiSplatRoute,
  HiraganaLetterRoute: HiraganaLetterRoute,
  JlptNRoute: JlptNRoute,
  JoyoGradeRoute: JoyoGradeRoute,
  KanjiLetterRoute: KanjiLetterRoute,
  KatakanaLetterRoute: KatakanaLetterRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
